services:
    backend:
      build:
        context: backend
      ports: 
        - "5000"
      environment:
        NODE_ENV: production  # Set NODE_ENV environment variable to 'production'
      deploy:
        replicas: 3
      
    nginx:
      image: nginx:latest
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
          - backend
      ports:
          - "8000:80"
